package sandboxdispatch

import (
	"context"
	"encoding/json"
	"net"
	"time"
)

// SubmitResultV2 is the terminal relay for the SAFE one-shot protocol. A
// confirmed result always includes both the bounded raw result and the
// dispatcher-owned kernel confirmation; retry and quarantine contain neither.
type SubmitResultV2 struct {
	Outcome      OutcomeV2
	Result       []byte
	Confirmation *LimitConfirmationV2
}

// V2RegistrationOptions names the immutable registration correlation fields.
// SupervisorHandoffID must identify an unused SCM_RIGHTS handoff already
// accepted by the dispatcher; it is never generated by this client.
type V2RegistrationOptions struct {
	ArtifactHash               string
	SandboxProfileRevision     string
	ObservationProfileRevision string
	SupervisorHandoffID        string
}

// SubmitV2 performs one v2 submit exchange against the physically separate
// submit listener. The dispatcher accepts no role-selection frame here.
func (s *Submitter) SubmitV2(ctx context.Context, job JobV2, payload []byte) (SubmitResultV2, bool, error) {
	if ctx == nil || ctx.Err() != nil || s.MaxPayloadBytes <= 0 || s.FrameTimeout <= 0 {
		return SubmitResultV2{}, false, ErrSubmitFailed
	}
	socketPath := s.V2SubmitSocketPath
	if socketPath == "" {
		return SubmitResultV2{}, false, ErrSubmitFailed
	}
	dialer := net.Dialer{Timeout: s.FrameTimeout}
	conn, err := dialer.DialContext(ctx, "unix", socketPath)
	if err != nil {
		if ctx.Err() != nil {
			return SubmitResultV2{}, false, ErrSubmitFailed
		}
		// No connection means no job or document bytes reached the dispatcher.
		// An unavailable service must not quarantine the source document. Once
		// connected, retain the conservative failure path unless the dispatcher
		// explicitly confirms a pre-transfer retry.
		return SubmitResultV2{}, true, nil
	}
	defer conn.Close()
	handshakeDeadline := time.Now().Add(s.FrameTimeout)
	if callerDeadline, ok := ctx.Deadline(); ok && callerDeadline.Before(handshakeDeadline) {
		handshakeDeadline = callerDeadline
	}
	if err := conn.SetDeadline(handshakeDeadline); err != nil {
		return SubmitResultV2{}, false, ErrSubmitFailed
	}
	jobBytes, err := json.Marshal(job)
	if err != nil || writeFrame(conn, kindJobV2, jobBytes) != nil {
		return SubmitResultV2{}, false, ErrSubmitFailed
	}
	headerBytes, err := json.Marshal(PayloadHeaderV2{LeaseID: job.LeaseID})
	if err != nil || writePayloadFrame(conn, headerBytes, payload) != nil {
		return SubmitResultV2{}, false, ErrSubmitFailed
	}
	// FrameTimeout covers only the initial job/payload handshake. A real parser
	// may legitimately run for the job's full lease window; terminal reads are
	// fenced by the job deadline and, when present, the caller deadline.
	terminalDeadline, err := parseTimestamp(job.DeadlineAt)
	if err != nil {
		return SubmitResultV2{}, false, ErrSubmitFailed
	}
	if callerDeadline, ok := ctx.Deadline(); ok && callerDeadline.Before(terminalDeadline) {
		terminalDeadline = callerDeadline
	}
	if !terminalDeadline.After(time.Now()) || conn.SetDeadline(terminalDeadline) != nil {
		return SubmitResultV2{}, false, ErrSubmitFailed
	}
	stopCancellation := context.AfterFunc(ctx, func() { _ = conn.SetDeadline(time.Now()) })
	defer stopCancellation()

	var (
		result      SubmitResultV2
		outcomeSeen bool
		resultSeen  bool
		limitsSeen  bool
	)
	for {
		kind, body, err := readFrameWith(conn, func(kind frameKind) int {
			if kind == kindResult {
				return s.MaxPayloadBytes
			}
			return maxFrameBody
		})
		if err != nil {
			return SubmitResultV2{}, false, ErrSubmitFailed
		}
		switch kind {
		case kindOutcome:
			if outcomeSeen {
				return SubmitResultV2{}, false, ErrSubmitFailed
			}
			if err := decodeStrict(body, &result.Outcome); err != nil || result.Outcome.Validate() != nil ||
				result.Outcome.LeaseID != job.LeaseID || result.Outcome.JobID != job.JobID ||
				result.Outcome.ParserRequest != job.ParserRequest || result.Outcome.OutputContract != job.ParserRequest.OutputContract ||
				!exactParserRequestInOutcome(body, job.ParserRequest) {
				return SubmitResultV2{}, false, ErrSubmitFailed
			}
			outcomeSeen = true
			switch result.Outcome.Handoff.TransferState {
			case TransferRetry:
				if resultSeen || limitsSeen {
					return SubmitResultV2{}, false, ErrSubmitFailed
				}
				return result, true, nil
			case TransferQuarantine:
				if resultSeen || limitsSeen {
					return SubmitResultV2{}, false, ErrSubmitFailed
				}
				return result, false, nil
			case TransferConfirmed:
				// Result and limits follow the terminal outcome on the relay.
			default:
				return SubmitResultV2{}, false, ErrSubmitFailed
			}
		case kindResult:
			if !outcomeSeen || result.Outcome.Handoff.TransferState != TransferConfirmed || resultSeen || int64(len(body)) > job.ParserRequest.MaxOutputBytes {
				return SubmitResultV2{}, false, ErrSubmitFailed
			}
			resultSeen = true
			result.Result = append([]byte(nil), body...)
		case kindLimits:
			if limitsSeen || !outcomeSeen || result.Outcome.Handoff.TransferState != TransferConfirmed || !resultSeen {
				return SubmitResultV2{}, false, ErrSubmitFailed
			}
			var confirmation LimitConfirmationV2
			if err := decodeStrict(body, &confirmation); err != nil || confirmation.Validate() != nil ||
				confirmation.LeaseID != job.LeaseID || confirmation.JobID != job.JobID ||
				confirmation.ParserRequest != job.ParserRequest || confirmation.WorkerID != derefString(result.Outcome.WorkerID) ||
				result.Outcome.RuntimeProfileHash == nil || confirmation.RuntimeProfileHash != *result.Outcome.RuntimeProfileHash ||
				result.Outcome.ExecutionConfirmationID == nil || confirmation.ExecutionConfirmationID != *result.Outcome.ExecutionConfirmationID ||
				result.Outcome.ResultDigest == nil || digestFor(result.Result) != *result.Outcome.ResultDigest {
				return SubmitResultV2{}, false, ErrSubmitFailed
			}
			result.Confirmation = &confirmation
			limitsSeen = true
			return result, false, nil
		default:
			return SubmitResultV2{}, false, ErrSubmitFailed
		}
	}
}

func derefString(value *string) string {
	if value == nil {
		return ""
	}
	return *value
}

// RegisterV2 connects to the registration listener selected by parser role and
// performs the versioned one-shot handshake. All authority-bearing fields are
// carried by one typed options value; there is no variadic compatibility path
// that can silently omit the supervisor handoff correlation.
func (w *WorkerClient) RegisterV2(ctx context.Context, workerID, parserType string, options V2RegistrationOptions) (*WorkerSession, error) {
	hello := RegisterHelloV2{
		SchemaVersion: RegistrationVersionV2, WorkerID: workerID, ParserType: parserType,
		ArtifactHash: options.ArtifactHash, SandboxProfileRevision: options.SandboxProfileRevision,
		ObservationProfileRevision: options.ObservationProfileRevision, SupervisorHandoffID: options.SupervisorHandoffID,
		OneShot: true, MaxLeases: 1, Capabilities: []string{CapabilityPullJob, CapabilityPushOutcome},
	}
	if err := hello.Validate(parserType); err != nil {
		return nil, ErrRegistrationRejected
	}
	if ctx == nil {
		return nil, ErrRegistrationRejected
	}
	deadline, bounded := ctx.Deadline()
	if !bounded || ctx.Err() != nil {
		return nil, ErrRegistrationRejected
	}
	socketPath := w.v2RegistrationSocket(parserType)
	if socketPath == "" {
		return nil, ErrRegistrationRejected
	}
	conn, err := (&net.Dialer{}).DialContext(ctx, "unix", socketPath)
	if err != nil {
		return nil, ErrRegistrationRejected
	}
	unixConn, ok := conn.(*net.UnixConn)
	if !ok {
		_ = conn.Close()
		return nil, ErrRegistrationRejected
	}
	if err := unixConn.SetDeadline(deadline); err != nil {
		_ = unixConn.Close()
		return nil, ErrRegistrationRejected
	}
	stopCancellation := context.AfterFunc(ctx, func() { _ = unixConn.SetDeadline(time.Now()) })
	helloBytes, err := json.Marshal(hello)
	if err != nil || writeFrame(unixConn, kindRegisterV2, helloBytes) != nil {
		_ = stopCancellation()
		_ = unixConn.Close()
		return nil, ErrRegistrationRejected
	}
	kind, body, err := readFrame(unixConn, maxFrameBody)
	if err != nil || kind != kindRegisterV2Accepted || string(body) != RegistrationAcceptedVersionV2 || ctx.Err() != nil {
		_ = stopCancellation()
		_ = unixConn.Close()
		return nil, ErrRegistrationRejected
	}
	_ = stopCancellation()
	if err := unixConn.SetDeadline(time.Time{}); err != nil {
		_ = unixConn.Close()
		return nil, ErrRegistrationRejected
	}
	return &WorkerSession{conn: unixConn, WorkerID: workerID, ParserType: parserType, maxPayloadBytes: w.MaxPayloadBytes, v2: true}, nil
}

// RegisterV2With is a descriptive alias for composition roots that prefer an
// explicitly named typed entry point.
func (w *WorkerClient) RegisterV2With(ctx context.Context, workerID, parserType string, options V2RegistrationOptions) (*WorkerSession, error) {
	return w.RegisterV2(ctx, workerID, parserType, options)
}

func (w *WorkerClient) v2RegistrationSocket(parserType string) string {
	switch parserType {
	case ParserTypeOffice:
		if w.V2OfficeRegistrationSocketPath != "" {
			return w.V2OfficeRegistrationSocketPath
		}
	case ParserTypePDF:
		if w.V2PDFRegistrationSocketPath != "" {
			return w.V2PDFRegistrationSocketPath
		}
	case ParserTypeOCR:
		if w.V2OCRRegistrationSocketPath != "" {
			return w.V2OCRRegistrationSocketPath
		}
	}
	return ""
}

// PullV2 receives exactly one offered and then transferred lease. The one-shot
// session cannot pull another lease after ReportV2 closes its peer socket.
func (w *WorkerSession) PullV2(ctx context.Context) (*LeaseV2, []byte, PayloadHeaderV2, error) {
	if !w.v2 || ctx == nil {
		return nil, nil, PayloadHeaderV2{}, ErrLeaseRejected
	}
	if deadline, ok := ctx.Deadline(); ok {
		if err := w.conn.SetReadDeadline(deadline); err != nil {
			return nil, nil, PayloadHeaderV2{}, ErrLeaseRejected
		}
		stop := context.AfterFunc(ctx, func() { _ = w.conn.SetReadDeadline(time.Now()) })
		defer stop()
	}
	kind, body, err := readFrame(w.conn, maxFrameBody)
	if err != nil || kind != kindLeaseV2 {
		return nil, nil, PayloadHeaderV2{}, ErrLeaseRejected
	}
	var offered LeaseV2
	if err := decodeStrict(body, &offered); err != nil || offered.Validate() != nil || offered.State != LeaseOffered || offered.WorkerID != w.WorkerID || offered.ParserRequest.ParserType != w.ParserType {
		return nil, nil, PayloadHeaderV2{}, ErrLeaseRejected
	}
	claimBytes, err := json.Marshal(Claim{LeaseID: offered.LeaseID, WorkerID: w.WorkerID})
	if err != nil || writeFrame(w.conn, kindClaim, claimBytes) != nil {
		return nil, nil, PayloadHeaderV2{}, ErrLeaseRejected
	}
	kind, body, err = readFrame(w.conn, maxFrameBody)
	if err != nil || kind != kindLeaseV2 {
		return nil, nil, PayloadHeaderV2{}, ErrLeaseRejected
	}
	var transferred LeaseV2
	if err := decodeStrict(body, &transferred); err != nil || transferred.Validate() != nil || transferred.State != LeaseTransferred || transferred.LeaseID != offered.LeaseID || transferred.JobID != offered.JobID || transferred.WorkerID != w.WorkerID || transferred.ParserRequest != offered.ParserRequest || !exactParserRequestInOutcome(body, offered.ParserRequest) {
		return nil, nil, PayloadHeaderV2{}, ErrLeaseRejected
	}
	header, payload, err := readPayloadFrameV2(w.conn, w.maxPayloadBytes)
	if err != nil || header.Validate() != nil || header.LeaseID != transferred.LeaseID {
		return nil, nil, PayloadHeaderV2{}, ErrLeaseRejected
	}
	w.v2StateMu.Lock()
	w.v2Lease = &transferred
	w.v2Header = header
	w.v2StateMu.Unlock()
	return &transferred, payload, header, nil
}

// ReportV2 sends at most one bounded result and the worker outcome, then closes
// the one-shot peer. Digest authority remains with the dispatcher so a forged
// digest is quarantined there rather than being silently trusted by the worker
// client.
func (w *WorkerSession) ReportV2(outcome OutcomeV2, result []byte) error {
	if !w.v2 {
		return ErrOutcomeRejected
	}
	w.v2StateMu.Lock()
	lease := w.v2Lease
	header := w.v2Header
	if lease == nil || outcome.Validate() != nil || outcome.LeaseID != lease.LeaseID || outcome.JobID != lease.JobID || outcome.ParserRequest != lease.ParserRequest || outcome.OutputContract != lease.ParserRequest.OutputContract {
		w.v2StateMu.Unlock()
		return ErrOutcomeRejected
	}
	if outcome.Handoff.TransferState == TransferRetry {
		if outcome.WorkerID != nil || outcome.ResultDigest != nil || outcome.RuntimeProfileHash != nil || outcome.ExecutionConfirmationID != nil || result != nil {
			w.v2StateMu.Unlock()
			return ErrOutcomeRejected
		}
	} else {
		if outcome.WorkerID == nil || *outcome.WorkerID != w.WorkerID || outcome.RuntimeProfileHash == nil || *outcome.RuntimeProfileHash != header.RuntimeProfileHash || outcome.ExecutionConfirmationID == nil || *outcome.ExecutionConfirmationID != header.ExecutionConfirmationID {
			w.v2StateMu.Unlock()
			return ErrOutcomeRejected
		}
		if outcome.Handoff.ConfirmationID != header.ExecutionConfirmationID {
			w.v2StateMu.Unlock()
			return ErrOutcomeRejected
		}
		if outcome.Handoff.TransferState == TransferConfirmed && len(result) == 0 {
			w.v2StateMu.Unlock()
			return ErrOutcomeRejected
		}
		if outcome.Handoff.TransferState == TransferQuarantine && result != nil {
			w.v2StateMu.Unlock()
			return ErrOutcomeRejected
		}
	}
	if result != nil {
		if err := writeResultFrame(w.conn, result, w.maxPayloadBytes); err != nil {
			w.v2StateMu.Unlock()
			return ErrOutcomeRejected
		}
	}
	outcomeBytes, err := json.Marshal(outcome)
	if err != nil || writeFrame(w.conn, kindOutcome, outcomeBytes) != nil {
		w.v2StateMu.Unlock()
		_ = w.conn.Close()
		return ErrOutcomeRejected
	}
	w.v2Lease = nil
	w.v2StateMu.Unlock()
	_ = w.conn.Close()
	return nil
}
