import { createElement } from "react";
import { renderToStaticMarkup } from "react-dom/server";
import { GovernedPresetPanelHost, SearchView, reduceGovernedRetention, type GovernedRetentionState, type WorkspaceDataState } from "./main";
let failures = 0;
const check = (ok: boolean, message: string) => { if (!ok) { failures++; console.error(`FAIL ${message}`); } };
const state = { phase: "loaded", snapshot: { kind: "ok", value: { id: "workspace-1", status: "ACTIVE", revision: 1, model_profiles: [] } }, sources: { kind: "ok", value: { sources: [], confirmation_context: {} } } } as unknown as WorkspaceDataState;
const renderSearch = (active: boolean) => renderToStaticMarkup(createElement(SearchView, { active, onOpenEvidence: () => {}, onOpenSources: () => {}, requestedWorkspaceID: "workspace-1", state }));
const host = renderToStaticMarkup(createElement(GovernedPresetPanelHost, { active: true, onSessionExpired: () => {}, requestedWorkspaceID: "workspace-1", revalidationKey: 0, state }));
const visible = renderSearch(true);
const disclosure = visible.indexOf('<details class="document-search-disclosure">');
check(host.includes("Ask company data"), "the governed heading is present");
check(disclosure >= 0 && disclosure < visible.indexOf('id="pilot-question"'), "document search is behind its disclosure");
check(disclosure >= 0 && !visible.slice(disclosure, disclosure + 80).includes(" open"), "document search is closed by default");
check(visible.includes('placeholder="Search documents"'), "document search keeps its document label");
check(!visible.includes("Live database checks") && !visible.includes("Ask live database") && !visible.includes("Ask a question about live company data"), "duplicated live copy is removed");
check(renderSearch(false).includes("hidden"), "the document view remains mounted while hidden");
const initial: GovernedRetentionState = { workspaceID: null, revision: null, phase: "pending", resetKey: 0 };
const pending = reduceGovernedRetention(initial, { workspaceID: "workspace-1", phase: "pending", revision: null });
const authorized = reduceGovernedRetention(pending, { workspaceID: "workspace-1", phase: "authorized", revision: 7 });
const away = reduceGovernedRetention(authorized, { workspaceID: "workspace-1", phase: "pending", revision: null });
const back = reduceGovernedRetention(away, { workspaceID: "workspace-1", phase: "authorized", revision: 7 });
const revised = reduceGovernedRetention(back, { workspaceID: "workspace-1", phase: "authorized", revision: 8 });
const denied = reduceGovernedRetention(revised, { workspaceID: "workspace-1", phase: "denied", revision: null });
check(away.phase === "pending" && away.revision === 7 && away.resetKey === authorized.resetKey, "revalidation hides while retaining the live result identity");
check(back.phase === "authorized" && back.revision === 7 && back.resetKey === authorized.resetKey, "same-revision return reveals without reset or resubmit");
check(revised.resetKey === back.resetKey + 1 && revised.revision === 8, "revision change resets retained state");
check(denied.phase === "denied" && denied.revision === null && denied.resetKey === revised.resetKey + 1, "denial clears retained state");
if (failures !== 0) throw new Error(`${failures} search-surface assertion(s) failed`);
console.log("search surface probe: PASS");
